name = input("name")
creature = input("creature")
thing_they_hate = input ("what do you dislike (thing)")
adjective = input ("adjective")
place = input ("location")
animal = input ("animal")
item = input ("object")
placs = input ("new location")
building = input ("building")
seven = input ("number")
print (f"there once was a fantastic {creature}. The adventure's name was {name} and they absolutely hated {thing_they_hate}. They desperately wanted to get rid of {thing_they_hate} from the world. Though it was such a random item {name} still dessided to make the journey to the {adjective} ostrige but the ostrige lived all the way at {place}. {name} would do it with it's pet Scribble the {animal}. Scribble was micheviuos and got into lots of trouble. Once Scirble at a {item} right out of {name}'s grasp. It was obvious to name that Scrible loved the {item}. {name} and Scribble started the long and tedious journey to {location}. It felt like they had to travel through mountains but others might say it was a short journey. When traviling through the platue they met the (seven) humanoied rhinoceros. There sure were a lot of them, (seven) hole rhinoceroses and they were angry. One of the rhinoceros bellowed "How dare ye trepassers trample the beutifule grass of the platue. I should fling you like a fly over (place) and into the (building) of the (adjective) ostrige" )
