name = input("name")
creature = input("creature")
thing_they_hate = input ("what do you dislike (thing)")
adjective = input ("adjective")
location = input ("location")
animal = input ("animal")
item = input ("object")
building = input ("building")
seven = input ("number")
thing = input ("new object")
friend = input ("new name")
emotion = input ("emotion")
shape = input ("shape")
print(f"there once was a fantastic {creature}. The adventure's name was {name} and they absolutely hated {thing_they_hate}. They desperately wanted to get rid of {thing_they_hate} from the world. Though it was such a random item {name} still dessided to make the journey to the {adjective} ostrich but the ostrich lived all the way at the {location}. {name} would do it with it's pet Scribble the {animal}. Scribble was micheviuos and got into lots of trouble. Once Scirble ate a {item} right out of {name}'s grasp. It was obvious to {name} that Scrible enjoyed the {item}. {name} and Scribble started the long and tedious journey to the {location}. It felt like they had to travel through mountains but others might say it was a short journey. When traviling through the platue they met the {seven} humanoied rhinoceros. There sure were a lot of them, {seven} hole rhinoceroses and they were angry. One of the rhinoceros bellowed 'How dare ye trepassers trample the beutifule grass of the platue. I should fling you like a fly over the platue and into the {building} of the {adjective} ostrich'. {name} and Scribble landed in a heap right in front of the {building}. The ostrich who was sitting on a {thing} jumped up with worry and croaked 'were'd you come from'. {name} told the ostrich about the rhinoceros and the desspised {thing_they_hate}. Than {name} asked kindley 'can i banish {thing_they_hate} from the world'. 'no we can't get ride of {thing_they_hate} from existence my friend {friend} loves it and, the rest of the world usses of course' stated the ostrich. 'noooooo' wailed {name}. Then the {adjective} ostrich said 'you should come inside and have tea i'm gonna take my mid-day nap'. The ostrich dug a hole in the ground and stuck it's head in. {name} and Scribble went inside the {building} and saw {friend} the hegchog. {friend} looked {emotion} and asked 'were is ostrich are they taking a nap agian'. {friend} went outside {emotion}ly to check in and look for ostrich. {name} sat down at the {shape} table and saw a tea cup. The tea cup looked up at {name} with it's tiny face and said 'hello there'. {name} jumped up with shock suprised by a talking tea cup. The tea cup smiled and wispered 'I heard you want to get rid of {thing_they_hate}'...")
